x=float^2(input("Enter the nmber of fresh bread purchased :"))
y=float^2(input("Enter the number of day old loaves purchased :"))
print("Regular price: 185.00")
print("Amount of new loaves:", x*185)
print("Amount of day old loaves:", y*185*0.4)
print("Total amount:", x*185+y*185*0.4)
